# Programe las funciones vendo y compro en el archivo bolsa.c

CFLAGS= -g -Wall -pedantic -std=c99
LDFLAGS= -g
LDLIBS= -lpthread

all: test-bolsa

test-bolsa: test-bolsa.o bolsa.o

clean:
	rm -f *.o test-bolsa
